### ISSUE TITLE
Enable default locations

### ISSUE THREAD

**Issue by BirgerK** [sbglasius/external-config#1]
It would be great if some locations would be searched by default for external configuration(s).

For this purpose I customized your grails.plugin.externalconfig.ExternalConfig this way:

```
...
@Override
    void setEnvironment(Environment environment) {
        println "start reading external config-file"
        List<String> defaultLocations = [
                "classpath:${appName}-config.properties",
                "classpath:${appName}-config.groovy",
                "file:${userHome}/.grails/${appName}-config.properties",
                "file:${userHome}/.grails/${appName}-config.groovy"]

        List locations = environment.getProperty('grails.config.locations', ArrayList, defaultLocations)
        String encoding = environment.getProperty('grails.config.encoding', String, 'UTF-8')

        for (location in locations) {
        ....
```

Maybe you got an idea how to add something like this.

Regards, Birger

**Comment by sbglasius** [comment]
Thank you for your idea. I will look into this shortly.

**Comment by snimavat** [comment]
I dont think the plugin should try to be any more intelligent and automatically add external configurations itself, plugin would provide just way to add external configs and apps can add whtever they want

**Comment by sbglasius** [comment]
I have decided that there should be no default locations as it may raise issues in existing configurations and pickup configurations that was not intended to be picked up.
