### ISSUE TITLE
Does not work with spring @Value annotation

### ISSUE THREAD

**Issue by Luxor** [sbglasius/external-config#2]
Steps to reproduce:
In application.yml 

```
some.value = 'initial'
```

In external/config.yml

```
some.value= 'overriden'
```

In someService:

```
@Value('${some.value'})
String value /// <-- initial

grailsApplication.config.getyProperty('some.value') // <--- overriden
```

**Comment by sbglasius** [comment]
Thank you for your bug-report. I will look into this shortly

**Comment by snimavat** [comment]
This was actually bug with the grails itself..

**Comment by bruno-lopes** [comment]
The same here. Any news on this? Also Spring Security Core configurations in external file doesn't get read in time. I had to put it in Application.groovy in order to work.

**Comment by bruno-lopes** [comment]
@Luxor I'm using grails 3.3.3 here, and this notation is working as expected here:

```groovy
@Value('${grails.plugin.test.code}')
final String code
```

The value is defined in an external file config.groovy this way:

```groovy
grails.plugin.test.code = "myCode"
```

But the value is defined only in one place (config.groovy) in my case. Perhaps it is related with #3? Did you try to define it in only one place? And with .groovy file?

@sbglasius Spring Security Core configurations are loaded correctly from external file in the right time. I was doing a mistake in the definition of the configurations. Sorry for my last comment.

**Comment by sbglasius** [comment]
Apparently not a bug in external-config
