### ISSUE TITLE
Is it possible to use logback.groovy configurations?

### ISSUE THREAD

**Issue by bruno-lopes** [sbglasius/external-config#22]
This is not a bug, but a question. I have different logback files per environment. In development mode, I would like to have it in a specific dir from my pc. In production, I would like to have it at my classpath. Is it possible to use the External Config plugin to achieve this? Thanks in advance.

**Comment by sbglasius** [comment]
I don't think it is, but I need to look into it.

**Comment by bruno-lopes** [comment]
I think a solution is to use something like this in application.groovy:

```groovy
environments {
    development {
         logging.config= "file:${System.getProperty('user.home')}/.grails/logback/logback.groovy"        
    }
    prod {
         logging.config= "classpath:logback/logback.groovy"
    }
}

```

I'll test and post the results.

**Comment by bruno-lopes** [comment]
@sbglasius. The solution I posted does work. I'm closing this issue, because it isn't a problem in the plugin. Thanks!
