### ISSUE TITLE
Allow regex in location paths

### ISSUE THREAD

**Issue by bruno-lopes** [sbglasius/external-config#24]
Currently, the plugin only allow the definition of an exact file path, as /home/bruno/.grails/config.groovy (or ~/.grails/config.groovy).

But, as an application grows, it make sense to use multiple configuration files, for instance, redis.groovy (to configure redis), ldap.groovy (to configure ldap), and so on. It increases readability and organization of the configurations.

Following Grails philosophy, it would be nice if each team could create a convention, and define for instance, that all configuration files begin with a prefix, like 'config-'. In this sense, the plugin should allow to define a location like this:

/home/bruno/.grails/config-*.groovy

This way, when someone needs to add a config file, if the file name follows the convention, it can be recognized without the need of changing application.groovy.

**Comment by bruno-lopes** [comment]
A possible implementation would be something like this:

https://stackoverflow.com/a/15598781

**Comment by sbglasius** [comment]
@bruno-lopes How would you guarantee load order if you are using wildcards? if the same configuration key is in two configuration files, but with different value, and wildcards are in place, which should load first?

**Comment by bruno-lopes** [comment]
@sbglasius, thanks for your response. I mentioned that as a possible solution, but in fact I really didn't test it. In my case, this is not a problem, because every configuration file has a unique set of keys, so the situation you mentioned does not occur.

But indeed, this is a real problem. I think you could create a convention, like lexicographical order, and apply this in the code. Also, another solution would be to define the regex to be something like this:

```
<PATTERN>-*[<LOAD_ORDER>].groovy
```

In my previous example, PATTERN equals to **config**, and LOAD_ORDER is defined by the user. The filenames would be something like:

config-redis[1].groovy
config-ldap[2].groovy
config-hibernate[3].groovy
config-hibernate-advanced[4].groovy
config-hibernate-advanced[5].groovy

This way, the user would be able to guarantee load order. In this situation, if config-hibernate-advanced[4].groovy and config-hibernate-advanced[5].groovy have the same config key, the final loaded value would be from config-hibernate-advanced[4].groovy, since it was defined to be loaded first.

**Comment by sbglasius** [comment]
@bruno-lopes That looks a bit too complicated, and in this scenario you might as well specify the full path in which order you want them loaded. 

The load order is only undetermined for each wild-card, and should be fairly easy to implement. I'll keep this ticket open for when I have a chance to work on it.
