### ISSUE TITLE
Consistent way to reference configuration properties defined in canonical files

### ISSUE THREAD

**Issue by ilPittiz** [sbglasius/external-config#26]
Let's assume in my `application.groovy` file (or either in `application.yml` with proper syntax) I defined a property

    host = 'app.domain.com'

I then defined a custom configuration `additionalConf.properties` file with content

    query = ?dummy
    baseUrl = https://${host}/path${query}

Then printing the value for `baseUrl` (in any Controller or Bootstrap):

    println Holders.config.baseUrl
    > https://app.domain.com/path?dummy

which is excellent.
When switching instead from `.properties` to `.groovy` file, with revised content as

    query = '?dummy'
    baseUrl = 'https://${host}/path${query}'

(basically adding quotes around strings), I get:

    println Holders.config.baseUrl
    > https://[:]/path?dummy

It would be really great to have the resulting behavior for the source `.groovy` file (and also `.yml`) be the same as the one for `.properties` file.

**Comment by sbglasius** [comment]
Dupplicates #5 and is being addressed

**Comment by sbglasius** [comment]
This is not the same issue as #5 thus reopening
