### ISSUE TITLE
Precedence for the the property defined in both: external config file and the one that's bundled in the war file should be reversed

### ISSUE THREAD

**Issue by bayshores** [sbglasius/external-config#3]
At present if you define same property in external config file and application.yml that's bundled in the application's war file, the property defined in the application.yml in war file takes precedence. I wish the property defined in the external config file could take the precedence. By the way, this plugin is quite useful and thanks for building it!

**Comment by sbglasius** [comment]
Thank you for your bug-report. I will look into this shortly

**Comment by avilches** [comment]
Hi, I agree. Until you fixed it, I've just resolve it removing the internal war config... thanks.

**Comment by sbglasius** [comment]
I have finally created a test app: https://github.com/sbglasius/external-config/commit/4758d83f11d5b7e6e56c87bcb17a90f2f8a0ca08 and I'm not able to reproduce this issue.

If I have a file: `$HOME/.grails/external-config-test.yml` with the content:
```
test:
  config:
    value: "From Home Config"
``` 
and I do a 
```
./gradlew assemble
 java -jar build/libs/external-config-test-0.1.war 
``` 
Then I will see the value `Value is: From Home Config` when visiting http://localhost:8080/test/index

If you can prove me wrong, I'll reopen the issue
