### ISSUE TITLE
Is there a way to reference external config from logback ?

### ISSUE THREAD

**Issue by danyyacoub** [sbglasius/external-config#33]
Hi,  
This is a question not a bug, but is there a way to reference external config file from logback.
I have an external properties file that contains the datasource, some variables I use in controllers and log configurations. Is there a way to retrieve this variables from logback ?
grails.util.Holders.applicationContext.getBean('grailsApplication') does not work.

**Comment by sbglasius** [comment]
No, the logback configuration is read earlier, where the framework is not yet started, thus you have no access to `grailsApplication`
