### ISSUE TITLE
Failed to introspect class: class external.config.Application

### ISSUE THREAD

**Issue by fabiocanella** [sbglasius/external-config#38]
Using grails 3.3.9 with external-config:1.3.0 or external-config:1.2.2 I have this error on startup.

Error creating bean with name 'grailsApplicationPostProcessor' defined in applicationname.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is org.grails.core.exceptions.GrailsRuntimeException: Failed to introspect class: class external.config.Application

I checked Application.groovy file but is clean...

I can't understand where is the error...

**Comment by sbglasius** [comment]
@fabiocanella Can you make a small separate project where the error occurs and push it to github. Then I can look into it. I have not seen it before, and there are lots of users of the plugin.

**Comment by fabiocanella** [comment]
Thank you, I have also another project where i'm using this plugin and is working fine, but in this one I can't understand where is the problem.... 
I fear I've made a wrong configuration somewhere in the past, or the project is dirty... I have already tried to do grails clean without results.

Do you have other suggestions ?
