### ISSUE TITLE
Misleading release description and wrong groupId

### ISSUE THREAD

**Issue by andersaaberg** [sbglasius/external-config#51]
https://github.com/sbglasius/external-config/releases/tag/2.0.1 has a misleading description: "No code changes, but has moved to a new repository and new coordinates.". There are actually some bugfixes included: https://github.com/sbglasius/external-config/compare/2.0.0...2.0.1 - which e.g. fixes https://github.com/sbglasius/external-config/issues/50 (and many thanks for that!)

the new artifact has a different groupId than mentioned in README.md - README.md says "dk.glasius.external-config" but the actual groupId is "dk.glasius": https://search.maven.org/search?q=a:external-config

PR to update the README.md: https://github.com/sbglasius/external-config/pull/52

**Comment by sbglasius** [comment]
Thank you. The PR was merged
