### ISSUE TITLE
The plugin does not work with Grails 5

### ISSUE THREAD

**Issue by bruno-lopes** [sbglasius/external-config#55]
I was using this plugin with Grails 4, and it does work like a charm.

But after updating to Grails 5, it stopped working.

Are there any plans to support Grails 5? Thanks in advance, and congratulations for this great plugin!

**Comment by sbglasius** [comment]
I'm already working on an upgrade. Stay tuned. 🙂

**Comment by bruno-lopes** [comment]
@sbglasius very very thanks! :smile:

**Comment by sbglasius** [comment]
New release: https://github.com/sbglasius/external-config/releases/tag/v3.0.0
